version: '3.8'

services:
    postgres:
        image: postgres:15
        container_name: postgres_cocos_challenge
        environment:
            POSTGRES_DB: cocos_challenge
            POSTGRES_USER: userroot
            POSTGRES_PASSWORD: pass
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    postgres_data:
